import type {PackageJson} from '@grogarden/gro/package_json.js';

export const package_json = {
	name: '@feltjs/felt-mural',
	description: 'a proof-of-concept Svelte component for collaborative drawing using Felt',
	version: '0.3.1',
	homepage: 'https://mural.felt.dev/',
	license: 'Unlicense',
	repository: {type: 'git', url: 'git+https://github.com/feltjs/felt-mural.git'},
	type: 'module',
	engines: {node: '>=20.7'},
	scripts: {
		start: 'gro dev',
		dev: 'gro dev',
		build: 'gro build',
		test: 'gro test',
		deploy: 'gro deploy',
	},
	files: ['dist'],
	peerDependencies: {'@grogarden/util': '*', svelte: '*'},
	devDependencies: {
		'@changesets/changelog-git': '^0.1.14',
		'@feltjs/eslint-config': '^0.4.0',
		'@fuz.dev/fuz': '^0.73.0',
		'@fuz.dev/fuz_code': '^0.3.1',
		'@fuz.dev/fuz_contextmenu': '^0.4.1',
		'@fuz.dev/fuz_dialog': '^0.3.1',
		'@fuz.dev/fuz_library': '^0.11.0',
		'@grogarden/gro': '^0.95.3',
		'@grogarden/util': '^0.15.0',
		'@sveltejs/adapter-static': '^2.0.3',
		'@sveltejs/kit': '^1.25.2',
		'@sveltejs/package': '^2.2.2',
		'@types/prismjs': '^1.26.1',
		'@typescript-eslint/eslint-plugin': '^6.8.0',
		'@typescript-eslint/parser': '^6.8.0',
		eslint: '^8.51.0',
		'eslint-plugin-svelte': '^2.34.0',
		prettier: '^3.0.3',
		'prettier-plugin-svelte': '^3.0.3',
		'prism-svelte': '^0.5.0',
		prismjs: '^1.29.0',
		svelte: '^4.2.1',
		'svelte-check': '^3.5.2',
		tslib: '^2.6.2',
		typescript: '^5.2.2',
		uvu: '^0.5.6',
	},
	eslintConfig: {root: true, extends: '@feltjs'},
	prettier: {
		plugins: ['prettier-plugin-svelte'],
		useTabs: true,
		printWidth: 100,
		singleQuote: true,
		bracketSpacing: false,
		overrides: [{files: 'package.json', options: {useTabs: false}}],
	},
	exports: {
		'./item.js': {default: './dist/item.js', types: './dist/item.d.ts'},
		'./Mural.svelte': {svelte: './dist/Mural.svelte', types: './dist/Mural.svelte.d.ts'},
		'./MuralItem.svelte': {
			svelte: './dist/MuralItem.svelte',
			types: './dist/MuralItem.svelte.d.ts',
		},
		'./MuralItemList.svelte': {
			svelte: './dist/MuralItemList.svelte',
			types: './dist/MuralItemList.svelte.d.ts',
		},
		'./MuralItemListItem.svelte': {
			svelte: './dist/MuralItemListItem.svelte',
			types: './dist/MuralItemListItem.svelte.d.ts',
		},
		'./package.gen.js': {default: './dist/package.gen.js', types: './dist/package.gen.d.ts'},
		'./package.js': {default: './dist/package.js', types: './dist/package.d.ts'},
		'./Scaled.svelte': {svelte: './dist/Scaled.svelte', types: './dist/Scaled.svelte.d.ts'},
		'./Surface.svelte': {svelte: './dist/Surface.svelte', types: './dist/Surface.svelte.d.ts'},
	},
} satisfies PackageJson;
